#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Nov 14 18:48:24 EST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim sim_test_axi_ip_behav -key {Behavioral:sim_1:Functional:sim_test_axi_ip} -tclbatch sim_test_axi_ip.tcl -log simulate.log"
xsim sim_test_axi_ip_behav -key {Behavioral:sim_1:Functional:sim_test_axi_ip} -tclbatch sim_test_axi_ip.tcl -log simulate.log

