#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Mon Dec 09 04:22:54 EST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim parser_sim_behav -key {Behavioral:sim_1:Functional:parser_sim} -tclbatch parser_sim.tcl -view /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/parser/parser_sim_behav.wcfg -log simulate.log"
xsim parser_sim_behav -key {Behavioral:sim_1:Functional:parser_sim} -tclbatch parser_sim.tcl -view /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/parser/parser_sim_behav.wcfg -log simulate.log

