webtalk_init -webtalk_dir /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ip_repo/edit_master_axi_test_v1_0.sim/sim_1/behav/xsim/xsim.dir/sim_test_axi_ip_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 20 18:44:38 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2615518" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211027694_1777504441_210661626_020" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d18def17-4a72-48a3-a6e4-0039919d69d9" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f40eae07d14e4932934a430bb6062096" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "60" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3844.789 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "3" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "19 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "3 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "35" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "0.83_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "218612_KB" -context "xsim\\usage"
webtalk_transmit -clientid 625136085 -regid "211027694_1777504441_210661626_020" -xml /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ip_repo/edit_master_axi_test_v1_0.sim/sim_1/behav/xsim/xsim.dir/sim_test_axi_ip_behav/webtalk/usage_statistics_ext_xsim.xml -html /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ip_repo/edit_master_axi_test_v1_0.sim/sim_1/behav/xsim/xsim.dir/sim_test_axi_ip_behav/webtalk/usage_statistics_ext_xsim.html -wdm /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ip_repo/edit_master_axi_test_v1_0.sim/sim_1/behav/xsim/xsim.dir/sim_test_axi_ip_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
