webtalk_init -webtalk_dir /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ethernet/ethernet.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-11-20 18:38:27" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2019.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211027694_1777504441_210661626_020" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "s40h64q66csjkt9dcbbiunhcoe" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2019.1_2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 14.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3639.062 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.117 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1574276346000" -context "sdk\\\\bsp/1574276346000"
webtalk_add_data -client sdk -key hwid -value "1572639618000" -context "sdk\\\\bsp/1574276346000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1574276346000"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\bsp/1574276346000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1574276346000"
webtalk_add_data -client sdk -key uid -value "1574276351000" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key hwid -value "1572639618000" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key bspid -value "1574276346000" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key apptemplate -value "lwip_echo_server" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1574276351000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1574293107333"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1574293107333"
webtalk_transmit -clientid 2875951498 -regid "211027694_1777504441_210661626_020" -xml /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ethernet/ethernet.sdk/webtalk/usage_statistics_ext_sdk.xml -html /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ethernet/ethernet.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /afs/athena.mit.edu/user/n/k/nkk/fpga_6115/HFT/ethernet/ethernet.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
