#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Nov 08 15:07:33 EST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim uart_sim_behav -key {Behavioral:sim_1:Functional:uart_sim} -tclbatch uart_sim.tcl -log simulate.log"
xsim uart_sim_behav -key {Behavioral:sim_1:Functional:uart_sim} -tclbatch uart_sim.tcl -log simulate.log

