#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 19 20:09:01 EST 2019
# SW Build 2615518 on Fri Aug  9 15:53:29 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto b7ae87e5902e46ae920651dbea441a10 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot sim_test_axi_ip_behav xil_defaultlib.sim_test_axi_ip xil_defaultlib.glbl -log elaborate.log"
xelab -wto b7ae87e5902e46ae920651dbea441a10 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot sim_test_axi_ip_behav xil_defaultlib.sim_test_axi_ip xil_defaultlib.glbl -log elaborate.log

